name: CI Build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

env:
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry

jobs:
# MAUI Android Build
  # build-android:
  #   runs-on: windows-2022
  #   name: Android Build
  #   steps:

  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Setup .NET
  #       uses: actions/setup-dotnet@v4
  #       with:
  #         dotnet-version: 6.0.x
          
  #     - name: Install MAUI Workload
  #       run: dotnet workload install maui --ignore-failed-sources

  #     - name: Restore Dependencies
  #       run: dotnet restore PristonToolsEU.sln

  #     - name: Build MAUI Android
  #       run: dotnet publish PristonToolsEU.sln -c Release -f net8.0-android --no-restore

  #     - name: Upload Android Artifact
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: mauibeach-android-ci-build
  #         path: bin/Release/net8.0-android/*Signed.a*

# MAUI Windows Build
  build-windows:
    runs-on: windows-2022
    name: Windows Build
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore PristonToolsEU.sln -r win-x64 /p:PublishReadyToRun=true

      - name: Build MAUI Windows
        run: dotnet publish PristonToolsEU.sln -c Release -f net8.0-windows10.0.19041.0 -r win-x64 --no-restore

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mauibeach-windows-ci-build
          path: bin/Release/net8.0-windows10.0.19041.0/win10-x64/AppPackages/**/*.msix

# MAUI iOS Build
  # build-ios:
  #   runs-on: macos-12
  #   name: iOS Build
  #   steps:

  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Setup .NET
  #       uses: actions/setup-dotnet@v4
  #       with:
  #         dotnet-version: 6.0.x

  #     - name: Install MAUI Workload
  #       run: dotnet workload install maui --ignore-failed-sources

  #     - name: Restore Dependencies
  #       run: dotnet restore PristonToolsEU.sln

  #     - name: Build MAUI iOS
  #       run: dotnet build PristonToolsEU.sln -c Release -f net8.0-ios --no-restore /p:buildForSimulator=True /p:packageApp=True /p:ArchiveOnBuild=False

  #     - name: Upload iOS Artifact
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: mauibeach-ios-ci-build
  #         path: bin/Release/net8.0-ios/iossimulator-x64/**/*.app

# MAUI MacCatalyst Build
  build-mac:
    runs-on: macos-12
    name: MacCatalyst Build
    steps:
    
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore PristonToolsEU.sln -r maccatalyst-x64;maccatalyst-arm64

      - name: Build MAUI MacCatalyst
        run: dotnet publish PristonToolsEU.sln -c Release -f net8.0-maccatalyst -r maccatalyst-x64;maccatalyst-arm64 --no-restore -p:BuildIpa=True

      - name: Upload MacCatalyst Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-ci-build
          path: bin/Release/net8.0-maccatalyst/maccatalyst-x64/publish/*.pkg
