name: CI Build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

env:
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry

jobs:
# MAUI Android Build
  # build-android:
  #   runs-on: windows-2022
  #   name: Android Build
  #   steps:

  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Setup .NET
  #       uses: actions/setup-dotnet@v4
  #       with:
  #         dotnet-version: 6.0.x
          
  #     - name: Install MAUI Workload
  #       run: dotnet workload install maui --ignore-failed-sources

  #     - name: Restore Dependencies
  #       run: dotnet restore src/PristonToolsEU.csproj

  #     - name: Build MAUI Android
  #       run: dotnet publish src/PristonToolsEU.csproj -c Release -f net8.0-android --no-restore

  #     - name: Upload Android Artifact
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: mauibeach-android-ci-build
  #         path: src/bin/Release/net8.0-android/*Signed.a*

# MAUI Windows Build
  build-windows:
    runs-on: windows-2022
    name: Windows Build
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources

      # - name: Restore Dependencies
      #   run: dotnet restore src/PristonToolsEU.csproj /p:PublishReadyToRun=true -r win-x64

      - name: Build MAUI Windows
        run: dotnet publish src/PristonToolsEU.csproj -f net8.0-windows10.0.19041.0 -c Release -p:WindowsPackageType=None -p:RuntimeIdentifierOverride=win10-x64
        # run: dotnet publish src/PristonToolsEU.csproj -c Release -f net8.0-windows10.0.19041.0 --no-restore -r win-x64 /p:EnableWindowsTargeting=true

      - name: Create zip
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: 'release-x64.zip'
          path: src/bin/Release/net8.0-windows10.0.19041.0/win10-x64/publish

      - name: Upload Release Assets
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: release-x64.zip

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mauibeach-windows-ci-build
          path: release-x64.zip

# MAUI iOS Build
  # build-ios:
  #   runs-on: macos-12
  #   name: iOS Build
  #   steps:

  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Setup .NET
  #       uses: actions/setup-dotnet@v4
  #       with:
  #         dotnet-version: 6.0.x

  #     - name: Install MAUI Workload
  #       run: dotnet workload install maui --ignore-failed-sources

  #     - name: Restore Dependencies
  #       run: dotnet restore src/PristonToolsEU.csproj

  #     - name: Build MAUI iOS
  #       run: dotnet build src/PristonToolsEU.csproj -c Release -f net8.0-ios --no-restore /p:buildForSimulator=True /p:packageApp=True /p:ArchiveOnBuild=False

  #     - name: Upload iOS Artifact
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: mauibeach-ios-ci-build
  #         path: src/bin/Release/net8.0-ios/iossimulator-x64/**/*.app

# MAUI MacCatalyst Build
  build-mac:
    runs-on: macos-12
    name: MacCatalyst Build
    steps:
    
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x

      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore src/PristonToolsEU.csproj -r maccatalyst-x64

      - name: Build MAUI MacCatalyst
        run: dotnet publish src/PristonToolsEU.csproj -c Release -f net8.0-maccatalyst -r maccatalyst-x64 --no-restore -p:BuildIpa=True

      - name: Upload Release Assets
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: "**/*.pkg"

      - name: Upload MacCatalyst Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-ci-build
          path: src/bin/Release/net8.0-maccatalyst/maccatalyst-x64/publish/*.pkg
